# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'OMSConference' do
  use_frameworks!

  # Pods for OMSConference
  pod 'Alamofire', '~> 5.0.0.beta.1'

  target 'OMSConferenceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
